version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: |
            gem install bundler
            bundle config set path ~/.bundle

      - restore_cache:
          keys:
            - pacer-{{ checksum "Gemfile.lock" }}
            - pacer-

      - run:
          name: Bundle
          command: bundle

      - save_cache:
          key: pacer-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle

      - run:
          name: Rubocop
          command: bundle exec rake rubocop

      - run:
          name: RSpec
          command: bundle exec rake spec
